name: Go

on:
  push:
    branches: [ next ]
  pull_request:
    branches: [ next ]

jobs:
#  lint:
#    - name: Check out code into the Go module directory
#      uses: actions/checkout@v2
#    - name: Run golangci-lint
#      uses: golangci/golangci-lint-action@v1.2.1

  test_and_coverage:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x, 1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v -coverprofile=coverage.out -covermode=count ./...
      - name: Convert coverage to lcov
        uses: jandelgado/gcov2lcov-action@v1.0.0
        with:
          infile: coverage.out
          outfile: coverage.lcov
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
